version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - AUTH_DRIVER=static
      - STATIC_API_KEY=b63d5a16-c20d-41b5-94d8-3d66a6490c95
      - STORAGE_DRIVER=static
    volumes:
      - ./user-service:/var/www/html
  

  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      kong-database:
        condition: service_healthy
    command: >
      sh -c "
      kong migrations bootstrap &&
      kong migrations up &&
      kong migrations finish &&
      kong start &&
      curl -i -X POST http://localhost:8001/services --data 'name=user-service' --data 'url=http://user-service:8080' &&
      curl -i -X POST http://localhost:8001/services/user-service/routes --data 'paths[]=/user-service' &&
      curl -i -X POST http://localhost:8001/services/user-service/plugins --data 'name=key-auth' &&
      curl -i -X POST http://localhost:8001/consumers --data 'username=user-service-consumer' &&
      curl -i -X POST http://localhost:8001/consumers/user-service-consumer/key-auth --data 'key=b63d5a16-c20d-41b5-94d8-3d66a6490c95'
      "
