version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - AUTH_DRIVER=static
      - STATIC_API_KEY=your_secure_api_key_here
      - STORAGE_DRIVER=static
    volumes:
      - ./user-service:/var/www/html
